### ISSUE TITLE
Problem with module "six"

### ISSUE THREAD

**Issue by josecurioso** [ldotlopez/service.subtitles.tusubtitulo#2]
Hi, first of all awesome work and great idea to separate all the logic behind accesing tusubtitulo from the addon. A few days ago I finished making my own version of the addon and just today I saw your work here and thought I should give it a try.
The thing is that, using my testing fresh installation of Kodi v17.3 on Windows 10 x64 I get [this error](https://pastebin.com/suQPrBFX) with the module "six"  and I thought you would be interested in taking a look (although maybe I did something wrong). 

Other than that it works flawlessly and I would recommend to create a Kodi repository for the addon and embed its \<extension> tags inside the addon.xml of your addon so everyone that installs it gets automatic updates.

Best, 
Jose

**Comment by ldotlopez** [comment]
I think it's a problem with the python version bundled with kodi-win, the six module is missing.

Try to copy [six.py](https://raw.githubusercontent.com/benjaminp/six/1.10.0/six.py) into 'C:\Users\jotaj\AppData\Roaming\Kodi\addons\service.subtitles.misubtitulo\resources\lib\' 

Tell me if it works and I will release a new version with six bundled in.

**Comment by josecurioso** [comment]
that fixes the "six" problem but now it fails with [this](https://pastebin.com/4tUsyEXj) message. Seems to be the "pkg_resources" that is also missing.

**Comment by ldotlopez** [comment]
Try with this version.

It's a "fat" package that includes every third-party related module.

[service.subtitles.misubtitulo.zip](https://github.com/ldotlopez/service.subtitles.tusubtitulo/files/1068092/service.subtitles.misubtitulo.zip)

**Comment by josecurioso** [comment]
I works prefectly now, thanks.
You might want to check out [this](https://forum.kodi.tv/showthread.php?tid=250936) for the changes tehy made to the python api that seems to be messing up the import.
